# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ZQU-Autodaka

on: 
    workflow_dispatch:
    schedule:
    - cron: '15 16 * * *'#每天北京时间0点15分打卡

   
#on:
  #watch:
    #types: started
  #push:
  #schedule:
    #- cron: '15 8 * * *'#北京时间0点15分自动打卡


jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7.15
      uses: actions/setup-python@v3
      with:
        python-version: "3.7.15"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        #pip install requests
        #pip install configparser
        #pip install json
        python -m pip install ddddocr
        #pip install time
        
        if ([ -f requirements.txt ]); then pip install -r requirements.txt; fi
    - name: auto-daka
      env:
          account: ${{ secrets.account }}
          #username: ${{ secrets.username }}
          #password: ${{ secrets.password }}
         # phonenumber: ${{ secrets.phonenumber }}
          SERVER: ${{ secrets.SERVER }}
          SCKEY: ${{ secrets.SCKEY }}
          #MAIL_NOTICE: ${{ secrets.MAI_NOTICE }}
         # MAILBOX: ${{ secrets.MAILBOX }}
      run: |
        python3 ./dsdk.py 
    - name: xianshi
      run: echo 打卡成功!
      
       
 
